apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: release-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: snaqvi_DEV
      jobs:
        - deploy-to-snaqvi_DEV
    - name: snaqvi_QA
      jobs:
        - deploy-to-snaqvi_QA
    - name: snaqvi_PROD
      jobs:
        - deploy-to-snaqvi_PROD
jobs:
  deploy-to-snaqvi_DEV:
    steps:
      - name: Deploy to snaqvi_DEV
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to snaqvi_DEV"
        kind: deploy
  deploy-to-snaqvi_QA:
    needs:
      - deploy-to-snaqvi_DEV
    steps:
      - name: Deploy to snaqvi_QA
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to snaqvi_QA"
        kind: deploy
  deploy-to-snaqvi_PROD:
    needs:
      - deploy-to-snaqvi_QA
    steps:
      - name: Deploy to snaqvi_PROD
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to snaqvi_PROD"
        kind: deploy
