apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: release-workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: snaqvi_DEV
      jobs:
        - deploy-to-snaqvi_DEV
        - Exit-Gate
    - name: snaqvi_QA
      jobs:
        - deploy-to-snaqvi_QA
        - Create-SNOW-Ticket
    - name: snaqvi_PROD
      jobs:
        - deploy-to-snaqvi_PROD
        - Wait-For-CR-Approval
jobs:
  deploy-to-snaqvi_DEV:
    steps:
      - name: Deploy to snaqvi_DEV
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to snaqvi_DEV env"
        kind: deploy
  deploy-to-snaqvi_QA:
    needs: Exit-Gate
    steps:
      - name: Deploy to snaqvi_QA
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to snaqvi_QA"
        kind: deploy
  deploy-to-snaqvi_PROD:
    needs: Create-SNOW-Ticket
    steps:
      - name: Deploy to snaqvi_PROD
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to snaqvi_PROD"
        kind: deploy
  Exit-Gate:
    needs: deploy-to-snaqvi_DEV
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  Create-SNOW-Ticket:
    needs: deploy-to-snaqvi_QA
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  Wait-For-CR-Approval:
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: ""
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
